# .golangci.yml

run:
  timeout: 5m
  issues-exit-code: 1

linters-settings:
  errcheck:
    exclude-functions:
      - fmt.Errorf
      - os.Exit
      - log.Fatalf
  gocyclo:
    min-complexity: 15
  govet:
    check-shadowing: true
  ineffassign:
    enabled: true
  goconst:
    min-len: 2
    min-occurrences: 2
  golint:
    min-confidence: 0.8
  gocritic:
    enabled-tags:
      - diagnostic
      - performance
  lll:
    line-length: 120
  misspell:
    locale: US
  staticcheck:
    checks: ['all']
  unused:
    checks: ['all']
  stylecheck:
    enabled: true

linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - gosimple
    - typecheck
    - unused
    - gocyclo
    - gofmt
    - goimports
    - ineffassign
    - lll
    - misspell
    - nakedret
    - unparam
    - gocritic
    - goconst
    - stylecheck
  disable:
    - depguard
    - dogsled
    - dupl
    - gochecknoglobals
    - gochecknoinits
    - gosec
    - maligned
    - prealloc
    - testpackage

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - golint
  exclude-use-default: false

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true

tests:
  skip-dirs:
    - vendor
  skip-files:
    - _test\.go

