services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build: .
    command: go run ./cmd/server/main.go
    develop:
      watch:
        - action: sync
          path: .
          target: ./user-management-api
          ignore:
            - .idea
            - user-management-api
        - action: rebuild
          path: Makefile
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SERVER_ADDRESS: ${SERVER_ADDRESS}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: db
      DATABASE_URL: ${DATABASE_URL}

volumes:
  postgres_data:
